export const MANAGED_APPLICATION_ENVIRONMENT_KEYS = [
  "ADMIN_REVIEW_TOKEN",
  "AWS_ACCESS_KEY_ID",
  "AWS_REGION",
  "AWS_SECRET_ACCESS_KEY",
  "CLICKUP_API_TOKEN",
  "CLICKUP_LIST_ID",
  "CONVEX_DEPLOY_KEY",
  "CONVEX_INGEST_SECRET",
  "CONVEX_URL",
  "COOLIFY_ORIENTAL_APPLICATION_UUID",
  "EVAL_JUDGE_MODEL",
  "IP_HASH_SECRET",
  "NEXT_PUBLIC_CONVEX_URL",
  "NEXT_PUBLIC_GA_MEASUREMENT_ID",
  "NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION",
  "NEXT_PUBLIC_SENTRY_DSN",
  "NEXT_PUBLIC_SENTRY_ENVIRONMENT",
  "NEXT_PUBLIC_TURNSTILE_SITE_KEY",
  "NODE_ENV",
  "OPENAI_API_KEY",
  "OPENAI_REALTIME_MODEL",
  "OPENAI_REALTIME_MODEL_CANDIDATE",
  "OPENAI_REALTIME_SPEED",
  "OPENAI_REALTIME_TRANSCRIPTION_MODEL",
  "OPENAI_REALTIME_VOICE",
  "OPS_ALERT_SLACK_CHANNEL_ID",
  "OWNER_AI",
  "OWNER_COMMUNITY",
  "OWNER_CULTURAL",
  "OWNER_EDUCATION",
  "OWNER_OTHER",
  "OWNER_PROGRAMME",
  "OWNER_TECHNOLOGY",
  "OWNER_TENANCY",
  "REDIS_URL",
  "SENTRY_AUTH_TOKEN",
  "SENTRY_DSN",
  "SENTRY_ENVIRONMENT",
  "SENTRY_ORG",
  "SENTRY_PROJECT",
  "SES_FROM_ADDRESS",
  "SES_REPLY_TO",
  "SLACK_BOT_TOKEN",
  "SLACK_CHANNEL_ID",
  "SMTP_HOST",
  "SMTP_PASSWORD",
  "SMTP_PORT",
  "SMTP_USER",
  "TEAM_NOTIFICATION_CC_EMAILS",
  "TEAM_NOTIFICATION_EMAIL",
  "TURNSTILE_SECRET_KEY",
  "TURNSTILE_SITE_KEY",
  "VOICE_EMAIL_CAPTURE_MODE",
  "VOICE_IDLE_GOODBYE_GRACE_MS",
  "VOICE_IDLE_TIMEOUT_MS",
  "VOICE_MAX_DURATION_MS",
  "VOICE_MODEL_CELL",
  "VOICE_REASONING_CELL",
  "VOICE_RUNTIME_PROFILE",
  "VOICE_VARIANT_PICKER",
] as const;

export type ManagedApplicationEnvironmentKey = (typeof MANAGED_APPLICATION_ENVIRONMENT_KEYS)[number];

export const DEPLOY_ONLY_APPLICATION_ENVIRONMENT_KEYS = new Set<ManagedApplicationEnvironmentKey>([
  "CONVEX_DEPLOY_KEY",
  "COOLIFY_ORIENTAL_APPLICATION_UUID",
  "SENTRY_AUTH_TOKEN",
]);

export function managedRuntimeEnvironmentFromEnv(env: Readonly<Record<string, string | undefined>>) {
  const expected = new Map<ManagedApplicationEnvironmentKey, string>();
  for (const key of MANAGED_APPLICATION_ENVIRONMENT_KEYS) {
    if (DEPLOY_ONLY_APPLICATION_ENVIRONMENT_KEYS.has(key)) continue;
    const value = env[key];
    if (typeof value === "string" && value.length > 0) expected.set(key, value);
  }
  return expected;
}

export function isManagedBuildTimeEnvironmentKey(key: ManagedApplicationEnvironmentKey) {
  return key.startsWith("NEXT_PUBLIC_");
}
